# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dafydd Prys
email: daf.p.thomas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development blog where I keep notes of aspects of development that I
  find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dafyddprys.github.io" # the base hostname & protocol for your site
github_username:  dafyddPrys

# Build settings
markdown: kramdown
